# Generated by Django 5.0.3 on 2024-06-03 00:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Someone', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Something', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=api.models.generate_unique_post_id, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
