# Generated by Django 5.0.3 on 2024-06-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tksm_user_email_alter_tksm_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='NA', max_length=500),
        ),
        migrations.DeleteModel(
            name='TKSM_User',
        ),
    ]
