name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up node.js
      uses: actions/setup-node@v4
    - name: Install node-related dependencies
      run: |
        npm i webpack webpack-cli --save-dev
        npm i @babel/core babel-loader @babel/preset-env @babel/preset-react --save-dev
        npm i react react-dom --save-dev
        npm install @babel/plugin-proposal-class-properties
        npm install react-router-dom
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install nltk vader
      run: |
        python -m nltk.downloader vader_lexicon
    - name: Run Tests
      run: |
        cd web_app && python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      run: |
      # TODO: Fill out deployment strategy
